package com.walley.app.data.backup

import com.walley.app.data.local.AccountEntity
import com.walley.app.data.local.AccountOperationEntity
import com.walley.app.data.local.AdHocBudgetEntity
import com.walley.app.data.local.AdHocBudgetItemEntity
import com.walley.app.data.local.AssetEntity
import com.walley.app.data.local.BudgetEntity
import com.walley.app.data.local.BudgetItemEntity
import com.walley.app.data.local.EquityNoteEntity
import com.walley.app.data.local.FinancialSnapshotEntity
import com.walley.app.data.local.InvestmentEntity
import com.walley.app.data.local.InvestmentTransactionEntity
import com.walley.app.data.local.LiabilityEntity
import com.walley.app.data.local.StrategyInvestmentLinkEntity
import com.walley.app.data.local.WatchedEquityEntity
import com.walley.app.domain.model.AccountTaxRate
import com.walley.app.domain.model.AccountType
import com.walley.app.domain.model.BudgetItemIcon
import com.walley.app.domain.model.BudgetSectionType
import com.walley.app.domain.model.BudgetStatus
import com.walley.app.domain.model.Currency
import com.walley.app.domain.model.EquityStatus
import com.walley.app.domain.model.IncomeCategory
import com.walley.app.domain.model.InvestmentCategory
import com.walley.app.domain.model.InvestmentTransactionType
import java.math.BigDecimal
import java.time.LocalDate

fun AccountEntity.toBackupDto() = AccountBackupDto(
    id = id,
    name = name,
    type = type.name,
    currency = currency.name,
    balanceMinorUnits = balanceMinorUnits,
    taxRate = taxRate.name,
    targetAmountMinorUnits = targetAmountMinorUnits,
    targetDate = targetDate?.toString(),
    isDefault = isDefault,
    commissionFlatMinorUnits = commissionFlatMinorUnits,
    commissionPercent = commissionPercent.toPlainString(),
    isVirtual = isVirtual,
    isClosed = isClosed
)

/** [newId] overrides the DTO's original id, since restore always re-inserts with a fresh autogenerated id. */
fun AccountBackupDto.toEntity(newId: Long = 0) = AccountEntity(
    id = newId,
    name = name,
    type = AccountType.valueOf(type),
    currency = Currency.valueOf(currency),
    balanceMinorUnits = balanceMinorUnits,
    taxRate = AccountTaxRate.valueOf(taxRate),
    targetAmountMinorUnits = targetAmountMinorUnits,
    targetDate = targetDate?.let(LocalDate::parse),
    isDefault = isDefault,
    commissionFlatMinorUnits = commissionFlatMinorUnits,
    commissionPercent = BigDecimal(commissionPercent),
    isVirtual = isVirtual,
    isClosed = isClosed
)

fun InvestmentEntity.toBackupDto() = InvestmentBackupDto(
    id = id,
    name = name,
    ticker = ticker,
    category = category.name,
    currency = currency.name,
    currentPrice = currentPrice.toPlainString(),
    accountId = accountId,
    lastPriceUpdate = lastPriceUpdate?.toString(),
    externalTicker = externalTicker
)

fun InvestmentBackupDto.toEntity(newId: Long = 0, remappedAccountId: Long?) = InvestmentEntity(
    id = newId,
    name = name,
    ticker = ticker,
    category = InvestmentCategory.valueOf(category),
    currency = Currency.valueOf(currency),
    currentPrice = BigDecimal(currentPrice),
    accountId = remappedAccountId,
    lastPriceUpdate = lastPriceUpdate?.let(LocalDate::parse),
    externalTicker = externalTicker
)

fun InvestmentTransactionEntity.toBackupDto() = InvestmentTransactionBackupDto(
    id = id,
    investmentId = investmentId,
    type = type.name,
    date = date.toString(),
    quantity = quantity.toPlainString(),
    pricePerUnit = pricePerUnit.toPlainString(),
    commission = commission.toPlainString()
)

fun InvestmentTransactionBackupDto.toEntity(remappedInvestmentId: Long) = InvestmentTransactionEntity(
    investmentId = remappedInvestmentId,
    type = InvestmentTransactionType.valueOf(type),
    date = LocalDate.parse(date),
    quantity = BigDecimal(quantity),
    pricePerUnit = BigDecimal(pricePerUnit),
    commission = BigDecimal(commission)
)

fun AssetEntity.toBackupDto() = AssetBackupDto(
    id = id,
    name = name,
    currency = currency.name,
    purchaseValueMinorUnits = purchaseValueMinorUnits,
    currentValueMinorUnits = currentValueMinorUnits,
    purchaseDate = purchaseDate.toString()
)

fun AssetBackupDto.toEntity() = AssetEntity(
    name = name,
    currency = Currency.valueOf(currency),
    purchaseValueMinorUnits = purchaseValueMinorUnits,
    currentValueMinorUnits = currentValueMinorUnits,
    purchaseDate = LocalDate.parse(purchaseDate)
)

fun LiabilityEntity.toBackupDto() = LiabilityBackupDto(
    id = id,
    name = name,
    currency = currency.name,
    originalAmountMinorUnits = originalAmountMinorUnits,
    currentBalanceMinorUnits = currentBalanceMinorUnits,
    startDate = startDate.toString()
)

fun LiabilityBackupDto.toEntity() = LiabilityEntity(
    name = name,
    currency = Currency.valueOf(currency),
    originalAmountMinorUnits = originalAmountMinorUnits,
    currentBalanceMinorUnits = currentBalanceMinorUnits,
    startDate = LocalDate.parse(startDate)
)

fun BudgetEntity.toBackupDto() = BudgetBackupDto(
    id = id,
    year = year,
    month = month,
    status = status.name,
    applyIncomeAccountEffects = applyIncomeAccountEffects,
    applyCostsAccountEffects = applyCostsAccountEffects,
    applySavingsAccountEffects = applySavingsAccountEffects,
    applyInvestmentsAccountEffects = applyInvestmentsAccountEffects
)

fun BudgetBackupDto.toEntity(newId: Long = 0) = BudgetEntity(
    id = newId,
    year = year,
    month = month,
    status = BudgetStatus.valueOf(status),
    applyIncomeAccountEffects = applyIncomeAccountEffects,
    applyCostsAccountEffects = applyCostsAccountEffects,
    applySavingsAccountEffects = applySavingsAccountEffects,
    applyInvestmentsAccountEffects = applyInvestmentsAccountEffects
)

fun BudgetItemEntity.toBackupDto() = BudgetItemBackupDto(
    id = id,
    budgetId = budgetId,
    section = section.name,
    name = name,
    amountMinorUnits = amountMinorUnits,
    currency = currency.name,
    accountId = accountId,
    paymentDay = paymentDay,
    paymentDayIsLastOfMonth = paymentDayIsLastOfMonth,
    paidAmountMinorUnits = paidAmountMinorUnits,
    incomeCategory = incomeCategory?.name,
    icon = icon?.name,
    isFinalized = isFinalized
)

fun BudgetItemBackupDto.toEntity(remappedBudgetId: Long, remappedAccountId: Long?) = BudgetItemEntity(
    budgetId = remappedBudgetId,
    section = BudgetSectionType.valueOf(section),
    name = name,
    amountMinorUnits = amountMinorUnits,
    currency = Currency.valueOf(currency),
    accountId = remappedAccountId,
    paymentDay = paymentDay,
    paymentDayIsLastOfMonth = paymentDayIsLastOfMonth,
    paidAmountMinorUnits = paidAmountMinorUnits,
    incomeCategory = incomeCategory?.let(IncomeCategory::valueOf),
    icon = icon?.let(BudgetItemIcon::valueOf),
    isFinalized = isFinalized
)

fun AdHocBudgetEntity.toBackupDto() = AdHocBudgetBackupDto(
    id = id,
    name = name,
    startDate = startDate.toString(),
    endDate = endDate.toString(),
    accountId = accountId,
    currency = currency.name,
    isCompleted = isCompleted,
    isDraft = isDraft
)

fun AdHocBudgetBackupDto.toEntity(newId: Long = 0, remappedAccountId: Long) = AdHocBudgetEntity(
    id = newId,
    name = name,
    startDate = LocalDate.parse(startDate),
    endDate = LocalDate.parse(endDate),
    accountId = remappedAccountId,
    currency = Currency.valueOf(currency),
    isCompleted = isCompleted,
    isDraft = isDraft
)

fun AdHocBudgetItemEntity.toBackupDto() = AdHocBudgetItemBackupDto(
    id = id,
    budgetId = budgetId,
    name = name,
    amountMinorUnits = amountMinorUnits,
    paidAmountMinorUnits = paidAmountMinorUnits,
    icon = icon?.name,
    accountId = accountId
)

fun AdHocBudgetItemBackupDto.toEntity(remappedBudgetId: Long, remappedAccountId: Long?) = AdHocBudgetItemEntity(
    budgetId = remappedBudgetId,
    name = name,
    amountMinorUnits = amountMinorUnits,
    paidAmountMinorUnits = paidAmountMinorUnits,
    icon = icon?.let(BudgetItemIcon::valueOf),
    accountId = remappedAccountId
)

fun AccountOperationEntity.toBackupDto() = AccountOperationBackupDto(
    id = id,
    accountId = accountId,
    date = date.toString(),
    description = description,
    amount = amount.toPlainString()
)

fun AccountOperationBackupDto.toEntity(remappedAccountId: Long) = AccountOperationEntity(
    accountId = remappedAccountId,
    date = LocalDate.parse(date),
    description = description,
    amount = BigDecimal(amount)
)

fun WatchedEquityEntity.toBackupDto() = WatchedEquityBackupDto(id = id, name = name, ticker = ticker)

fun WatchedEquityBackupDto.toEntity(newId: Long = 0) = WatchedEquityEntity(id = newId, name = name, ticker = ticker)

fun EquityNoteEntity.toBackupDto() = EquityNoteBackupDto(
    id = id,
    equityId = equityId,
    date = date.toString(),
    status = status.name,
    note = note
)

fun EquityNoteBackupDto.toEntity(remappedEquityId: Long) = EquityNoteEntity(
    equityId = remappedEquityId,
    date = LocalDate.parse(date),
    status = EquityStatus.valueOf(status),
    note = note
)

fun StrategyInvestmentLinkEntity.toBackupDto() = StrategyInvestmentLinkBackupDto(
    equityId = equityId,
    investmentId = investmentId
)

fun StrategyInvestmentLinkBackupDto.toEntity(remappedEquityId: Long, remappedInvestmentId: Long) =
    StrategyInvestmentLinkEntity(equityId = remappedEquityId, investmentId = remappedInvestmentId)

fun FinancialSnapshotEntity.toBackupDto() = FinancialSnapshotBackupDto(
    id = id,
    budgetId = budgetId,
    year = year,
    month = month,
    baseCurrency = baseCurrency.name,
    cashAndCheckingMinorUnits = cashAndCheckingMinorUnits,
    savingsMinorUnits = savingsMinorUnits,
    investmentsMinorUnits = investmentsMinorUnits,
    assetsMinorUnits = assetsMinorUnits,
    liabilitiesMinorUnits = liabilitiesMinorUnits,
    netWorthMinorUnits = netWorthMinorUnits,
    incomeMinorUnits = incomeMinorUnits,
    incomeRelatedExpensesMinorUnits = incomeRelatedExpensesMinorUnits,
    disposableIncomeMinorUnits = disposableIncomeMinorUnits,
    salaryIncomeMinorUnits = salaryIncomeMinorUnits,
    dividendsIncomeMinorUnits = dividendsIncomeMinorUnits,
    interestIncomeMinorUnits = interestIncomeMinorUnits,
    otherIncomeMinorUnits = otherIncomeMinorUnits,
    investmentGrowthMinorUnits = investmentGrowthMinorUnits
)

/**
 * [remappedBudgetId] falls back to 0 (no matching restored budget) since a snapshot's budgetId
 * is only used to look up the source budget's year/month for historical display and tolerates
 * not resolving to a live row.
 */
fun FinancialSnapshotBackupDto.toEntity(remappedBudgetId: Long) = FinancialSnapshotEntity(
    budgetId = remappedBudgetId,
    year = year,
    month = month,
    baseCurrency = Currency.valueOf(baseCurrency),
    cashAndCheckingMinorUnits = cashAndCheckingMinorUnits,
    savingsMinorUnits = savingsMinorUnits,
    investmentsMinorUnits = investmentsMinorUnits,
    assetsMinorUnits = assetsMinorUnits,
    liabilitiesMinorUnits = liabilitiesMinorUnits,
    netWorthMinorUnits = netWorthMinorUnits,
    incomeMinorUnits = incomeMinorUnits,
    incomeRelatedExpensesMinorUnits = incomeRelatedExpensesMinorUnits,
    disposableIncomeMinorUnits = disposableIncomeMinorUnits,
    salaryIncomeMinorUnits = salaryIncomeMinorUnits,
    dividendsIncomeMinorUnits = dividendsIncomeMinorUnits,
    interestIncomeMinorUnits = interestIncomeMinorUnits,
    otherIncomeMinorUnits = otherIncomeMinorUnits,
    investmentGrowthMinorUnits = investmentGrowthMinorUnits
)
