package com.walley.app.data.backup

import androidx.room.withTransaction
import com.walley.app.data.datastore.IntegrationsDataStore
import com.walley.app.data.datastore.SettingsDataStore
import com.walley.app.data.local.WALLEY_DB_SCHEMA_VERSION
import com.walley.app.data.local.WalleyDatabase
import com.walley.app.domain.model.BudgetSectionType
import com.walley.app.domain.model.Currency
import java.math.BigDecimal
import java.time.Instant
import javax.inject.Inject
import kotlinx.coroutines.flow.first

/** Builds a full [BackupSnapshot] from the local database + settings, and restores one back. */
class BackupSerializer @Inject constructor(
    private val database: WalleyDatabase,
    private val settingsDataStore: SettingsDataStore,
    private val integrationsDataStore: IntegrationsDataStore
) {

    suspend fun buildSnapshot(): BackupSnapshot {
        val settings = BackupSettingsDto(
            darkModeOverride = settingsDataStore.darkModeOverride.first(),
            baseCurrency = settingsDataStore.baseCurrency.first().name,
            includeSavingsInNetWorth = settingsDataStore.includeSavingsInNetWorth.first(),
            fixedCostsTargetPercent = settingsDataStore.categoryTarget(BudgetSectionType.FIXED_COSTS).first()?.toPlainString(),
            otherCostsTargetPercent = settingsDataStore.categoryTarget(BudgetSectionType.OTHER_COSTS).first()?.toPlainString(),
            savingsTargetPercent = settingsDataStore.categoryTarget(BudgetSectionType.SAVINGS).first()?.toPlainString(),
            investmentsTargetPercent = settingsDataStore.categoryTarget(BudgetSectionType.INVESTMENTS).first()?.toPlainString(),
            yahooFinanceEnabled = integrationsDataStore.yahooFinanceEnabled.first()
        )

        return BackupSnapshot(
            schemaVersion = WALLEY_DB_SCHEMA_VERSION,
            exportedAt = Instant.now().toString(),
            accounts = database.accountDao().observeAll().first().map { it.toBackupDto() },
            investments = database.investmentDao().observeAll().first().map { it.toBackupDto() },
            investmentTransactions = database.investmentDao().observeAllTransactions().first().map { it.toBackupDto() },
            investmentPriceHistory = database.investmentPriceHistoryDao().observeAll().first().map { it.toBackupDto() },
            assets = database.assetDao().observeAll().first().map { it.toBackupDto() },
            liabilities = database.liabilityDao().observeAll().first().map { it.toBackupDto() },
            budgets = database.budgetDao().observeBudgets().first().map { it.toBackupDto() },
            budgetItems = database.budgetDao().observeAllItems().first().map { it.toBackupDto() },
            adHocBudgets = database.adHocBudgetDao().observeBudgets().first().map { it.toBackupDto() },
            adHocBudgetItems = database.adHocBudgetDao().observeAllItems().first().map { it.toBackupDto() },
            accountOperations = database.accountOperationDao().observeAll().first().map { it.toBackupDto() },
            watchedEquities = database.watchedEquityDao().observeEquities().first().map { it.toBackupDto() },
            equityNotes = database.watchedEquityDao().observeAllNotes().first().map { it.toBackupDto() },
            strategyInvestmentLinks = database.watchedEquityDao().observeAllStrategyLinks().first().map { it.toBackupDto() },
            financialSnapshots = database.financialSnapshotDao().observeAll().first().map { it.toBackupDto() },
            settings = settings
        )
    }

    /**
     * Destructive: wipes all local tables, then bulk-inserts the snapshot back in FK-dependency
     * order, remapping each entity's original autogenerated id to whatever fresh id Room assigns
     * on re-insert (ids aren't preserved across a restore, so every child row's foreign key is
     * rewritten via the parent's old-id -> new-id map built right after that parent is inserted).
     */
    suspend fun restoreSnapshot(snapshot: BackupSnapshot) {
        database.withTransaction {
            database.clearAllTables()

            val accountIdMap = database.accountDao()
                .insertAll(snapshot.accounts.map { it.toEntity() })
                .let { newIds -> snapshot.accounts.map { it.id }.zip(newIds).toMap() }

            database.assetDao().insertAll(snapshot.assets.map { it.toEntity() })
            database.liabilityDao().insertAll(snapshot.liabilities.map { it.toEntity() })

            val investmentIdMap = database.investmentDao()
                .insertAll(snapshot.investments.map { it.toEntity(remappedAccountId = it.accountId?.let(accountIdMap::get)) })
                .let { newIds -> snapshot.investments.map { it.id }.zip(newIds).toMap() }

            database.investmentDao().insertTransactions(
                snapshot.investmentTransactions.map {
                    it.toEntity(remappedInvestmentId = investmentIdMap.getValue(it.investmentId))
                }
            )

            database.investmentPriceHistoryDao().insertAll(
                snapshot.investmentPriceHistory.map {
                    it.toEntity(remappedInvestmentId = investmentIdMap.getValue(it.investmentId))
                }
            )

            database.accountOperationDao().insertAll(
                snapshot.accountOperations.map { it.toEntity(remappedAccountId = accountIdMap.getValue(it.accountId)) }
            )

            val equityIdMap = database.watchedEquityDao()
                .insertEquities(snapshot.watchedEquities.map { it.toEntity() })
                .let { newIds -> snapshot.watchedEquities.map { it.id }.zip(newIds).toMap() }

            database.watchedEquityDao().insertNotes(
                snapshot.equityNotes.map { it.toEntity(remappedEquityId = equityIdMap.getValue(it.equityId)) }
            )

            database.watchedEquityDao().insertStrategyLinks(
                snapshot.strategyInvestmentLinks.map {
                    it.toEntity(
                        remappedEquityId = equityIdMap.getValue(it.equityId),
                        remappedInvestmentId = investmentIdMap.getValue(it.investmentId)
                    )
                }
            )

            val budgetIdMap = database.budgetDao()
                .insertBudgets(snapshot.budgets.map { it.toEntity() })
                .let { newIds -> snapshot.budgets.map { it.id }.zip(newIds).toMap() }

            database.budgetDao().insertItems(
                snapshot.budgetItems.map {
                    it.toEntity(
                        remappedBudgetId = budgetIdMap.getValue(it.budgetId),
                        remappedAccountId = it.accountId?.let(accountIdMap::get)
                    )
                }
            )

            val adHocBudgetIdMap = database.adHocBudgetDao()
                .insertBudgets(snapshot.adHocBudgets.map { it.toEntity(remappedAccountId = accountIdMap.getValue(it.accountId)) })
                .let { newIds -> snapshot.adHocBudgets.map { it.id }.zip(newIds).toMap() }

            database.adHocBudgetDao().insertItems(
                snapshot.adHocBudgetItems.map {
                    it.toEntity(
                        remappedBudgetId = adHocBudgetIdMap.getValue(it.budgetId),
                        remappedAccountId = it.accountId?.let(accountIdMap::get)
                    )
                }
            )

            database.financialSnapshotDao().insertAll(
                snapshot.financialSnapshots.map { it.toEntity(remappedBudgetId = budgetIdMap[it.budgetId] ?: 0L) }
            )
        }

        restoreSettings(snapshot.settings)
    }

    private suspend fun restoreSettings(settings: BackupSettingsDto) {
        settings.darkModeOverride?.let { settingsDataStore.setDarkModeOverride(it) }
        settingsDataStore.setBaseCurrency(Currency.valueOf(settings.baseCurrency))
        settingsDataStore.setIncludeSavingsInNetWorth(settings.includeSavingsInNetWorth)
        settingsDataStore.setCategoryTarget(BudgetSectionType.FIXED_COSTS, settings.fixedCostsTargetPercent?.let(::BigDecimal))
        settingsDataStore.setCategoryTarget(BudgetSectionType.OTHER_COSTS, settings.otherCostsTargetPercent?.let(::BigDecimal))
        settingsDataStore.setCategoryTarget(BudgetSectionType.SAVINGS, settings.savingsTargetPercent?.let(::BigDecimal))
        settingsDataStore.setCategoryTarget(BudgetSectionType.INVESTMENTS, settings.investmentsTargetPercent?.let(::BigDecimal))
        integrationsDataStore.setYahooFinanceEnabled(settings.yahooFinanceEnabled)
    }
}
